### ISSUE TITLE
Installation on Windows using MSYS fails

### ISSUE THREAD

**Issue by paeder92** [rstoneback/pysatCDF#10]
Hello,

I am desparately trying to install pysatCDF on Windows 10 with Miniconda 2.7 and CDF Software Distribution 3.6.4. I installed MSYS, updated twice, downloaded some build tools using pacman, set up the PATH variables as specified in the instructions and started the installation. The rather lengthy output is uploaded here:

https://pastebin.com/TxR5D5my

There seems to be a lot of missing references that, as far as I understand, ultimately lead to the failure of the setup. Am I doing something wrong here or is this a bug?

**Comment by rstoneback** [comment]
The issue is that they are still using the Microsoft VC compiler. MSVC compiled C code won't link against gfortran compiled fortran code.  They need to set up their python build environment to use the mingw compiler.

  1.
C:\Users\Pati\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\Pati\Desktop\pysatCDF-0.3.0\pysatCDF-0.3.0\build\lib.win-amd64-2.7\pysatCDF\include -Ibuild\src.win-amd64-2.7\build\src.win-amd64-2.7\pysatCDF -IC:\Users\Pati\Miniconda2\lib\site-packages\numpy\core\include -IC:\Users\Pati\Miniconda2\include -IC:\Users\Pati\Miniconda2\PC /Tcbuild\src.win-amd64-2.7\pysatCDF\fortran_cdfmodule.c /Fobuild\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\pysatCDF\fortran_cdfmodule.obj
  2.
C:\Users\Pati\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\Pati\Desktop\pysatCDF-0.3.0\pysatCDF-0.3.0\build\lib.win-amd64-2.7\pysatCDF\include -Ibuild\src.win-amd64-2.7\build\src.win-amd64-2.7\pysatCDF -IC:\Users\Pati\Miniconda2\lib\site-packages\numpy\core\include -IC:\Users\Pati\Miniconda2\include -IC:\Users\Pati\Miniconda2\PC /Tcbuild\src.win-amd64-2.7\build\src.win-amd64-2.7\pysatCDF\fortranobject.c /Fobuild\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\build\src.win-amd64-2.7\pysatCDF\fortranobject.obj

On Jul 27, 2018, at 11:53 AM, paeder92 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

I am desparately trying to install pysatCDF on Windows 10 with Miniconda 2.7 and CDF Software Distribution 3.6.4. I installed MSYS, updated twice, downloaded some build tools using pacman, set up the PATH variables as specified in the instructions and started the installation. The rather lengthy output is uploaded here:

https://pastebin.com/TxR5D5my

There seems to be a lot of missing references that, as far as I understand, ultimately lead to the failure of the setup. Am I doing something wrong here or is this a bug?
